### ISSUE TITLE
Data (data.h5) is missing

### ISSUE THREAD

**Issue by tzpranto** [LearningMaker/DeepTheft#1]
data.h5 file is missing in the shared google drive.
https://drive.google.com/drive/folders/1MEuaUYt_js9meAMut9WIERhtnlIn_hqK

**Comment by dakangaa** [comment]
Authors give another URL for downloading dataset : 
https://zenodo.org/records/14334986?preview=1&token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjFkNDNhNGM4LTI5NmYtNDVmYy04Njg0LTEyYmNlY2MzM2MzZiIsImRhdGEiOnt9LCJyYW5kb20iOiIyZjZmZDNhMWQxNWU2OTM5YTMyNWFiMzllY2NjZmY4OSJ9.m5FXwzGPETjAMh8_YUU4r7OkoFvb-Iaaj_ijDj-pMyYG5kjMwVNLdIxO94_MkUars4C9xeSOng_FMux2gGqLKA

**Comment by tzpranto** [comment]
Thanks a lot.
